# Generated by Django 3.1.4 on 2021-03-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0002_auto_20210319_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(related_name='movie_likes', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='watched',
            field=models.ManyToManyField(related_name='movie_watched', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(related_name='movie_watchlist', to='movies.Movie'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_score', to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='scores',
            field=models.ManyToManyField(to='users.Score'),
        ),
    ]
