# Generated by Django 3.1.4 on 2021-03-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_landscape'),
        ('users', '0003_auto_20210319_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_likes', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watched',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_watched', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_watchlist', to='movies.Movie'),
        ),
    ]
