# Generated by Django 3.1.4 on 2021-03-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210325_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='scores',
            field=models.ManyToManyField(blank=True, null=True, to='users.Score'),
        ),
    ]
