# Generated by Django 3.1.4 on 2021-03-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_artist_views'),
        ('users', '0005_auto_20210325_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='artist_followed',
            field=models.ManyToManyField(blank=True, null=True, related_name='artist_followed', to='movies.Artist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='artist_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='artist_likes', to='movies.Artist'),
        ),
    ]
