# Generated by Django 3.1.4 on 2021-04-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210411_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='artist_followed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='artist_likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='critic_followed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='critic_likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='review_likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='watched',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='watchlist',
        ),
    ]
