# Generated by Django 3.1.4 on 2021-04-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210421_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
