# Generated by Django 3.1.4 on 2021-09-03 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0060_auto_20210903_1134'),
        ('users', '0009_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='artists_followed',
            field=models.ManyToManyField(related_name='artists_followed', to='movies.Artist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='artists_liked',
            field=models.ManyToManyField(related_name='artists_liked', to='movies.Artist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='films_liked',
            field=models.ManyToManyField(related_name='films_liked', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='films_watched',
            field=models.ManyToManyField(related_name='films_watched', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='films_watchlist',
            field=models.ManyToManyField(related_name='films_watchlist', to='movies.Movie'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField(default=0)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='scores',
            field=models.ManyToManyField(to='users.Score'),
        ),
    ]
