# Generated by Django 3.1.4 on 2021-09-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210908_0941'),
        ('users', '0010_auto_20210903_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='articles_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='articles_like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='articles_liked',
            field=models.ManyToManyField(related_name='articles_liked', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews_like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews_liked',
            field=models.ManyToManyField(related_name='reviews_liked', to='articles.Review'),
        ),
    ]
