# Generated by Django 3.1.4 on 2021-10-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0069_review_is_spoiler'),
        ('users', '0012_auto_20211011_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='FilmScore',
        ),
    ]
