# Generated by Django 3.1.4 on 2021-10-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0069_review_is_spoiler'),
        ('users', '0013_auto_20211012_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='scores',
            new_name='film_scores',
        ),
        migrations.CreateModel(
            name='SeriesScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField(default=0)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.series')),
            ],
        ),
    ]
