# Generated by Django 3.1.4 on 2021-10-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211012_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='series_scores',
            field=models.ManyToManyField(to='users.SeriesScore'),
        ),
    ]
