# Generated by Django 3.1.4 on 2021-10-15 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0069_review_is_spoiler'),
        ('users', '0017_auto_20211015_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='artists_followed',
            field=models.ManyToManyField(blank=True, null=True, related_name='artists_followed', to='movies.Artist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='artists_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='artists_liked', to='movies.Artist'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='film_scores',
            field=models.ManyToManyField(blank=True, null=True, to='users.FilmScore'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='films_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='films_liked', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='films_watched',
            field=models.ManyToManyField(blank=True, null=True, related_name='films_watched', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='films_watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='films_watchlist', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='series_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_liked', to='movies.Series'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='series_scores',
            field=models.ManyToManyField(blank=True, null=True, to='users.SeriesScore'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='series_watched',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_watched', to='movies.Series'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='series_watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_watchlist', to='movies.Series'),
        ),
    ]
