# Generated by Django 3.1.4 on 2021-10-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210908_0941'),
        ('movies', '0069_review_is_spoiler'),
        ('users', '0018_auto_20211015_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='articles_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles_liked', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reviews_disliked',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviews_disliked', to='movies.Review'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reviews_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviews_liked', to='movies.Review'),
        ),
    ]
