# Generated by Django 3.1.4 on 2021-10-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20211015_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='articles_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='articles_like_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='articles_liked',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reviews_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reviews_like_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
