# Generated by Django 3.1.4 on 2021-11-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0069_review_is_spoiler'),
        ('users', '0020_auto_20211015_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='films_watched',
            field=models.ManyToManyField(blank=True, null=True, related_name='films_watched', to='users.FilmDate'),
        ),
    ]
