# Generated by Django 3.1.4 on 2021-03-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210321_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='landscape',
            field=models.ImageField(blank=True, null=True, upload_to='movies/%Y/%m/%d'),
        ),
    ]
