# Generated by Django 3.1.4 on 2021-03-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_landscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
