# Generated by Django 3.1.4 on 2021-03-30 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210328_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='watchlisted',
            new_name='watchlist',
        ),
    ]
