# Generated by Django 3.1.4 on 2021-03-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210330_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
