# Generated by Django 3.1.4 on 2021-04-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_review_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
