# Generated by Django 3.1.4 on 2021-04-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='in_theater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
