# Generated by Django 3.1.4 on 2021-04-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20210412_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
    ]
