# Generated by Django 3.1.4 on 2021-04-22 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0019_comment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=90)),
                ('releasedate', models.DateField(blank=True, null=True)),
                ('season_count', models.IntegerField(default=1)),
                ('episode_count', models.IntegerField(default=1)),
                ('view_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('check_count', models.IntegerField(default=0)),
                ('watchlist_count', models.IntegerField(default=0)),
                ('score_count', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/%Y/%m/%d')),
                ('landscape', models.ImageField(blank=True, null=True, upload_to='movies/%Y/%m/%d')),
                ('trailer', models.CharField(blank=True, max_length=200, null=True)),
                ('is_released', models.BooleanField(default=False)),
                ('on_tv', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_created_by', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(blank=True, null=True, to='movies.Genre')),
                ('production', models.ManyToManyField(blank=True, null=True, to='movies.Production')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.rating')),
            ],
        ),
    ]
