# Generated by Django 3.1.4 on 2021-04-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.series'),
        ),
    ]
