# Generated by Django 3.1.4 on 2021-04-23 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0021_member_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='follow_count',
            new_name='views',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='check_count',
            new_name='views',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_by',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='check_count',
            new_name='views',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='score',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='score_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='watchlist_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='score',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='score',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='series',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='series',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='series',
            name='score_count',
        ),
        migrations.RemoveField(
            model_name='series',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='series',
            name='watchlist_count',
        ),
        migrations.AddField(
            model_name='artist',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='artist_follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='artist_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='checks',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_comments', to='movies.Comment'),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='scores',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_scores', to='movies.Score'),
        ),
        migrations.AddField(
            model_name='movie',
            name='watchlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='review_comments', to='movies.Comment'),
        ),
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.ManyToManyField(related_name='review_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='series',
            name='checks',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='series',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_comments', to='movies.Comment'),
        ),
        migrations.AddField(
            model_name='series',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='series',
            name='scores',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_scores', to='movies.Score'),
        ),
        migrations.AddField(
            model_name='series',
            name='watchlists',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_watchlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(related_name='review_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='series',
            name='landscape',
            field=models.ImageField(blank=True, null=True, upload_to='series/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='series/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
