# Generated by Django 3.1.4 on 2021-04-23 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20210423_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='member',
            name='role_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='series',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_actors', to='movies.Member'),
        ),
        migrations.AddField(
            model_name='movie',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_members', to='movies.Member'),
        ),
        migrations.AddField(
            model_name='series',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_actors', to='movies.Member'),
        ),
        migrations.AddField(
            model_name='series',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_members', to='movies.Member'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=100, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.artist')),
            ],
        ),
    ]
