# Generated by Django 3.1.4 on 2021-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20210423_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='is_finished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
    ]
