# Generated by Django 3.1.4 on 2021-04-26 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0029_auto_20210426_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='review_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='review_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
