# Generated by Django 3.1.4 on 2021-05-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_auto_20210426_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='series',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
