# Generated by Django 3.1.4 on 2021-05-10 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_auto_20210508_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='series',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='series',
            name='checks',
        ),
        migrations.RemoveField(
            model_name='series',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='series',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='series',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='series',
            name='description',
        ),
        migrations.RemoveField(
            model_name='series',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='series',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='series',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='series',
            name='is_released',
        ),
        migrations.RemoveField(
            model_name='series',
            name='landscape',
        ),
        migrations.RemoveField(
            model_name='series',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='series',
            name='members',
        ),
        migrations.RemoveField(
            model_name='series',
            name='name',
        ),
        migrations.RemoveField(
            model_name='series',
            name='on_tv',
        ),
        migrations.RemoveField(
            model_name='series',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='series',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='series',
            name='production',
        ),
        migrations.RemoveField(
            model_name='series',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='series',
            name='releasedate',
        ),
        migrations.RemoveField(
            model_name='series',
            name='score',
        ),
        migrations.RemoveField(
            model_name='series',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='series',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='series',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='series',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='series',
            name='views',
        ),
        migrations.RemoveField(
            model_name='series',
            name='watchlists',
        ),
        migrations.AddField(
            model_name='series',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
