# Generated by Django 3.1.4 on 2021-05-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0034_auto_20210510_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='occupation',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='production',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
