# Generated by Django 3.1.4 on 2021-05-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_auto_20210510_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='in_theater',
            new_name='is_playing',
        ),
    ]
