# Generated by Django 3.1.4 on 2021-05-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0037_tempfilm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempfilm',
            name='type',
        ),
        migrations.AddField(
            model_name='tempfilm',
            name='filmid',
            field=models.IntegerField(default=0),
        ),
    ]
