# Generated by Django 3.1.4 on 2021-05-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0040_tempartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempartist',
            name='artistid',
            field=models.IntegerField(default=0),
        ),
    ]
