# Generated by Django 3.1.4 on 2021-05-12 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0041_tempartist_artistid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='tempartist',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='tempartist',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='tempartist',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tempartist',
            name='views',
        ),
    ]
