# Generated by Django 3.1.4 on 2021-05-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0042_auto_20210512_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ManyToManyField(null=True, to='movies.Occupation'),
        ),
    ]
