# Generated by Django 3.1.4 on 2021-05-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0046_tempmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='member',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='tempactor',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='tempmember',
            name='movie',
        ),
        migrations.AddField(
            model_name='actor',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.film'),
        ),
        migrations.AddField(
            model_name='actor',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.series'),
        ),
        migrations.AddField(
            model_name='member',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.film'),
        ),
        migrations.AddField(
            model_name='member',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.series'),
        ),
        migrations.AddField(
            model_name='tempactor',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.film'),
        ),
        migrations.AddField(
            model_name='tempactor',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.series'),
        ),
        migrations.AddField(
            model_name='tempmember',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.film'),
        ),
        migrations.AddField(
            model_name='tempmember',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.series'),
        ),
    ]
