# Generated by Django 3.1.4 on 2021-08-31 05:27

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0052_auto_20210831_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='views',
            new_name='view_count',
        ),
        migrations.AddField(
            model_name='movie',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
