# Generated by Django 3.1.4 on 2021-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0055_auto_20210831_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmember',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
