# Generated by Django 3.1.4 on 2021-09-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0056_castmember_is_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
