# Generated by Django 3.1.4 on 2021-09-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0057_auto_20210902_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='views',
            new_name='view_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='likes',
        ),
        migrations.AddField(
            model_name='artist',
            name='facebook_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='follow_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
