# Generated by Django 3.1.4 on 2021-09-02 06:14

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0058_auto_20210902_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
