# Generated by Django 3.1.4 on 2021-09-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0063_auto_20210906_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='occupation',
            new_name='occupations',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dislikes',
            new_name='dislikers',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='likers',
        ),
        migrations.RenameField(
            model_name='crewmember',
            old_name='role',
            new_name='roles',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='production',
            new_name='productions',
        ),
    ]
