# Generated by Django 3.1.4 on 2021-09-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0064_auto_20210906_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='film_comments', to='movies.Comment'),
        ),
    ]
