# Generated by Django 3.1.4 on 2021-10-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0068_auto_20211011_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
