# Generated by Django 3.1.4 on 2021-12-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0069_review_is_spoiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheaterUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('theater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.theater')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.platform')),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='platforms',
            field=models.ManyToManyField(blank=True, null=True, to='movies.PlatformUrl'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='theaters',
            field=models.ManyToManyField(blank=True, null=True, to='movies.TheaterUrl'),
        ),
    ]
