# Generated by Django 3.1.4 on 2021-12-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0070_auto_20211216_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='background',
            field=models.CharField(default='#000', max_length=100),
        ),
    ]
