# Generated by Django 3.1.4 on 2022-06-20 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0073_auto_20211216_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='count',
        ),
        migrations.RemoveField(
            model_name='occupation',
            name='count',
        ),
        migrations.RemoveField(
            model_name='production',
            name='count',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='count',
        ),
    ]
